name: col864_proj
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anywidget=0.9.18
  - aom=3.7.1
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.0
  - certifi=2025.10.5
  - cffi=2.0.0
  - cloudpickle=3.1.1
  - comm=0.2.3
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - dav1d=1.2.1
  - deepdiff=8.6.1
  - expat=2.7.1
  - farama-notifications=0.0.4
  - ffmpeg=6.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.16
  - giflib=5.2.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.2
  - intel-openmp=2023.0.0
  - ipywidgets=8.1.7
  - jax-jumpy=1.0.0
  - jpeg=9f
  - jupyter-ui-poll=1.0.0
  - jupyterlab_widgets=3.0.15
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.8.2
  - libass=0.17.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libdrm=2.4.125
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenjpeg=2.5.4
  - libopenvino=2023.2.0
  - libopenvino-auto-batch-plugin=2023.2.0
  - libopenvino-auto-plugin=2023.2.0
  - libopenvino-hetero-plugin=2023.2.0
  - libopenvino-intel-cpu-plugin=2023.2.0
  - libopenvino-intel-gpu-plugin=2023.2.0
  - libopenvino-ir-frontend=2023.2.0
  - libopenvino-onnx-frontend=2023.2.0
  - libopenvino-paddle-frontend=2023.2.0
  - libopenvino-pytorch-frontend=2023.2.0
  - libopenvino-tensorflow-frontend=2023.2.0
  - libopenvino-tensorflow-lite-frontend=2023.2.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=3.21.12
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtheora=1.2.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libva=2.21.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - magma=2.6.2
  - mkl=2022.2.1
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nccl=2.27.3.1
  - ncurses=6.5
  - nettle=3.9.1
  - ninja=1.13.1
  - ocl-icd=2.3.3
  - ocl-icd-system=1.0.0
  - opencl-headers=2025.06.13
  - openh264=2.4.0
  - openjpeg=2.5.4
  - openssl=3.5.4
  - p11-kit=0.24.1
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - psygnal=0.14.2
  - pthread-stubs=0.3
  - pugixml=1.14
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.18
  - python_abi=3.10
  - pytorch-mutex=1.0
  - readline=8.3
  - requests=2.32.5
  - rerun-sdk=0.26.2
  - setuptools=80.9.0
  - sleef=3.9.0
  - snappy=1.1.10
  - sqlite=3.50.2
  - svt-av1=1.8.0
  - tbb=2021.8.0
  - tesseract=5.2.0
  - tk=8.6.14
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - beautifulsoup4==4.14.2
      - catkin-pkg==1.1.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cmake==4.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.1.1
      - decorator==5.2.1
      - detr==0.0.1
      - diffusers==0.35.2
      - dill==0.4.0
      - distro==1.9.0
      - dm-control==1.0.34
      - dm-env==1.6
      - dm-tree==0.1.9
      - docutils==0.22.2
      - draccus==0.10.0
      - einops==0.8.1
      - etils==1.13.0
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fasteners==0.20
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - gym-aloha==0.1.3
      - gym-notices==0.1.0
      - gymnasium==1.2.2
      - h11==0.16.0
      - h5py==3.15.1
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hydra-core==1.2.0
      - idna==3.11
      - imageio==2.22.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - lerobot==0.4.0
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mediapy==1.2.4
      - mergedeep==1.3.4
      - mujoco==3.3.7
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - numcodecs==0.13.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygame==2.1.2
      - pygments==2.19.2
      - pymunk==6.2.1
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - regex==2025.10.23
      - rerun-notebook==0.26.2
      - rospkg==1.6.0
      - safetensors==0.7.0
      - scikit-image==0.19.3
      - scipy==1.15.3
      - sentry-sdk==2.42.1
      - shapely==1.8.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - termcolor==3.2.0
      - tifffile==2025.5.10
      - toml==0.10.2
      - torch==2.7.1
      - torchcodec==0.5
      - torchvision==0.22.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.3.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - vq-bet==0.1.0
      - wandb==0.21.4
      - wcwidth==0.2.14
      - wrapt==2.0.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==2.18.3
      - zipp==3.23.0
prefix: /home/ghost404/miniconda3/envs/col864_proj
